### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by zeph00** [AndreMiras/tubedl#1]
Hi, rather a noob here.
Am currently looking to set up a website which does exactly what your project does, free of charge of course. Tried installing it via different approaches, but I seem to to something wrong. Could you possible add more "steps" in order to guide the less tech-savvy people (like me?). I'll be keeping a close eye. Thanks!

PS: Love your work, keep it up!!

**Comment by AndreMiras** [comment]
Hi zeph00,
Can you tell me more about your issues, what have you tried, what were your error messages.
TubeDL is built on top of the Django framework (https://www.djangoproject.com/). Django is very well documented, if you can run a Django hello world project, you shouldn't have any issue running TubeDL.

**Comment by zeph00** [comment]
Hi Andre,

Thanks for the reply, happy new year by the way!
I am looking to deploy this site first on a Windows Azure server, and once configured properly, copy the image and deploy it on a commercial server. These are the steps I've taken:

1) Download the Django Stack 1.7.1-dev (Ubuntu 14.04) from VMDepot onto my Windows Azure account
2) Drop the above image onto a Virtual Machine (2 core, 3.5GB memory)
3) Follow the steps mentioned here: https://devcenter.heroku.com/articles/getting-started-with-django#start-a-django-app-inside-a-virtualenv
4) Everything goes smooth until step "pip install django-toolbelt", I get an error:
![untitled](https://cloud.githubusercontent.com/assets/10375138/5639265/03e7abb4-960b-11e4-9708-4f0ec476e115.png)

After this, I can't continue onwards. Every next step goes wrong. What is it that I am doing wrong?

Thanks!

**Comment by zeph00** [comment]
If I were to give you access to a DigitalOcean VPS, would you be able to install it properly for me? I can pay of course. Please let me know in a PM. Also, if possible, I'd like to watch how you set it up for educational purposes.

Thanks!

**Comment by AndreMiras** [comment]
You probably have this error because you miss python-dev (apt-get install python-dev).
Also, django-toolbelt is OK for Heroku (which is a PaaS platform, I think Azure also have one PaaS offer), but if you have a VPS you probably won't need it.
I don't know Azure cloud very much, but if you have access to a  shell on your Ubuntu then just:

```
apt-get install python-dev
```

then:

```
pip install -r requirements.txt
```

Yes I can help installing it on your VPS if you give me an access to it.

**Comment by zeph00** [comment]
Thanks for the support Andre, managed to figure it out!

**Comment by zeph00** [comment]
Hey Andre,

I've made a public site for this, however I was wondering if you are able to optimize it (make it look better, being able to upgrade to the latest youtube-dl version, HD/SD download features) and the alike. If so, please leave me your contact details in order for us to communicate better. Of course, you shall be paid accordingly.

Thanks,
Zeph.

**Comment by AndreMiras** [comment]
You can drop me a email with more details andre [dot] miras [at] gmail [dot] com
