### ISSUE TITLE
My url is not supporting 😢

### ISSUE THREAD

**Issue by cvatricks** [AndreMiras/tubedl#11]
https://www.zee5.com/tvshows/details/sathya/0-6-1339/sathya-episode-26-april-02-2019-full-episode/0-1-195480

**Comment by AndreMiras** [comment]
Yes that's right, here is the list of supported sites so far 
https://tubedl.herokuapp.com/dl/supported_sites/

**Comment by cvatricks** [comment]
I'm requesting you to please add support for Zee5.

**Comment by AndreMiras** [comment]
Hi @cvatricks then you better ask the upstream library https://github.com/ytdl-org/youtube-dl/issues/
