### ISSUE TITLE
NOT an issue but a request

### ISSUE THREAD

**Issue by Neney22** [AndreMiras/tubedl#5]
Is there a possible way that we can get this software but in PHP, I want to try this on my website so bad!!

**Comment by AndreMiras** [comment]
Yes I saw some projects on Github doing it. Search for youtube-dl PHP.
But you will somehow have to run some Python code because the underlying library is written in Python.

**Comment by Neney22** [comment]
Would it be possible to run this project in a Shared server?. My hoster is hostgator and  CPanel is what Its given to upload my website but Im not sure if it supports python and if so how would I upload it?

**Comment by AndreMiras** [comment]
I don't think it would run on a PHP shared hosting server.
But it might be the opportunity for you to give a try to Python web development.
You may also want to give it a try on Heroku, just click the "Deploy to Heroku" button.
Last but not least, I think I've seen a Youtube-dl web API somewhere on Github, maybe you could just try consume it.
