### ISSUE TITLE
crunchyroll download it does not work | youtube_dl.utils.DownloadError

### ISSUE THREAD

**Issue by VortexHiman** [AndreMiras/tubedl#9]
[https://i.ibb.co/JvWMwFW/Sin-t-tulo2.png](url)  error img

Error details
<class 'youtube_dl.utils.DownloadError'>

ERROR: Unable to extract video_title; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

PD: Can you make a tutorial on how to install TubeDL in heroku?

**Comment by AndreMiras** [comment]
Could you please share the video URL you tried that is erroring?
Regarding the deployment on Heroku, it should normally be just clicking that button from the readme file

**Comment by VortexHiman** [comment]
this is the url : https://www.crunchyroll.com/es-es/jojos-bizarre-adventure/episode-1-dio-the-invader-652081

**Comment by VortexHiman** [comment]
pressing to unfold in heroku asks me for this information: https://i.ibb.co/H4BcCdY/Sin-t-tulo.png
What I can do? pd: hablas español?

**Comment by AndreMiras** [comment]
Sentry is an error reporting service, that's the way you get notified about users having troubles.
You can subscribe to a free account here http://sentry.io/
Then create a project and it will give you a project ID and key.
Also I've fixed the issue with your video download

**Comment by VortexHiman** [comment]
clicking download gives error after a few seconds and does not download anything  img: https://i.ibb.co/mBxdzf7/errordl.png

**Comment by AndreMiras** [comment]
Then it could be that the download is too large or too slow to be processed before server connection times out.
Sometimes you can get some luck retrying 1 minutes later, but for this video it looks like we're out of luck and there's no much we can do about it for now

**Comment by VortexHiman** [comment]
Is there no way to increase that time? At least 7 minutes.
If I create my Heroku application, where should I modify it to change those settings?

**Comment by AndreMiras** [comment]
Technically yes, but not under the (Heroku) free plans unfortunately
